coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        # Only check coverage on relevant file changes
        paths:
          - "lib/"
          - "spec/"
    patch:
      default:
        target: auto
        threshold: 1%
        # Only check patch coverage for code files
        paths:
          - "lib/"
          - "spec/"
        # Allow empty reports to pass
        if_no_uploads: success
        if_not_found: success

# Ignore certain paths completely
ignore:
  - "*.md"
  - "*.yml"
  - "*.gemspec"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: true  # Only comment when there are coverage changes
  require_base: false
  require_head: true
